COMBINE=True
COUNT=True
DESEQ=True
CALCULATE=True
POOL=True
DRAWPVALCUTOFF=False
SINGLEMOTIF=False
OUTPUT='./'
BEDDIR='/full/path/to/BEDS/'
BEDS=['/full/path/to/BEDS/'+'BEDNAME1.bed','/full/path/to/BEDS/'+'BEDNAME2.bed']
BAMDIR='/full/path/to/BAMS/'
BAM1=['/full/path/to/BAMS/'+'CONDITION1_rep1.sorted.bam','/full/path/to/BAMS/'+'CONDITION1_rep2.sorted.bam']
LABEL1='Treatment 1'
BAM2=['/full/path/to/BAMS/'+'CONDITION2_rep1.sorted.bam','/full/path/to/BAMS/'+'CONDITION2_rep2.sorted.bam']
LABEL2='Treatment 2'
FDRCUTOFF=0.1
PVALCUTOFF=0.1
LARGEWINDOW=1500.0
SMALLWINDOW=150.0
